image: ghcr.io/attuneengineering/open-agent:main
ports:
  - port: 8888
    onOpen: ignore
  - port: 5000
    onOpen: ignore
tasks:
  - init: git remote set-url origin https://$GITHUB_TOKEN@github.com/AttuneEngineering/open-agent.git
  - command: cowsay namaste 🙏