image: ghcr.io/attuneengineering/open-agent:main
ports:
  - port: 8888
    onOpen: ignore
  - port: 5000
    onOpen: ignore
tasks:
  - name: "jupyter"
    command: >
      git remote set-url origin https://$GITHUB_TOKEN@github.com/AttuneEngineering/open-agent.git &&
      echo "alias launch-jupyter='source /workspace/open-agent/bin/jupyter-lab.sh'" >> ~/.bashrc &&
      source ~/.bashrc &&
      cowsay namaste 🙏
